name: Test - custom CIDRs

on:
  workflow_dispatch:
    inputs:
      enterprise:
        description: GitHub Enterprise
        default: goodcorp
        required: true
        
      token:
        description: GitHub token
        required: true
  
jobs:
  update_allow_list:
    name: Update Enterprise IP Allow List
    runs-on: ubuntu-22.04
    
    steps:
      - name: Mask Token
        run: |
          echo "::add-mask::${{ github.event.inputs.token }}"
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update IP Allow List
        uses: ./
        with:
          github_token: ${{ github.event.inputs.token }}
          enterprise_slug: ${{ github.event.inputs.enterprise }}
          custom_cidrs: |
            192.168.10.0/24,
            192.168.11.0/24,
            192.168.12.0/24,
          
          custom_cidrs_label: 'Testing Custom CIDRs'

      - name: Update IP Allow List - default label
        uses: ./
        with:
          github_token: ${{ github.event.inputs.token }}
          enterprise_slug: ${{ github.event.inputs.enterprise }}
          custom_cidrs: |
            192.168.13.0/24,


      - name: Update IP Allow List including meta
        uses: ./
        with:
          github_token: ${{ github.event.inputs.token }}
          enterprise_slug: ${{ github.event.inputs.enterprise }}
          custom_cidrs: 192.168.100.0/24
          metadata_section: hooks
  
